######################################################################
# Automatically generated by qmake (3.0) ?? ???. 5 14:59:00 2019
######################################################################

TEMPLATE = app
TARGET = qtremote
INCLUDEPATH += .

# Input
SOURCES += main.cpp MainWindow.cpp

HEADERS += MainWindow.h

QT += widgets
